name: Master branch quality check

on:
  push:
    branches: [master]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean & build
        run: mvn clean install

      - name: Static code analysis (Checkstyle)
        run: mvn checkstyle:check

      - name: Unit + integration tests
        run: mvn verify
