server:
  port: 8083

spring:
  application:
    name: transaction-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: transaction_keyspace
      local-datacenter: datacenter1
      schema-action: create-if-not-exists
      username: cassandra
      password: cassandra

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
