version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=banking-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10

  cassandra-init:
    image: cassandra:4.1
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init.cql:/init.cql
    command: >
      bash -c "
        echo 'Waiting for Cassandra to be ready...'
        until cqlsh cassandra -e 'describe keyspaces' > /dev/null 2>&1; do
          echo 'Still waiting...'
          sleep 5
        done
        echo 'Cassandra is ready. Running initialization...'
        cqlsh cassandra -f ./init.cql
        echo 'Initialization completed.'
      "
    restart: "no"

volumes:
  cassandra_data:
