global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-apps'
    static_configs:
      - targets:
          - 'host.docker.internal:8081'  # account-service
          - 'host.docker.internal:8082'  # user-service
          - 'host.docker.internal:8083'  # transaction-service
    metrics_path: /actuator/prometheus

  - job_name: 'eureka-service'
    static_configs:
      - targets: ['host.docker.internal:8761']
    metrics_path: /actuator/prometheus

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /actuator/prometheus
