name: Deploy branch CI

on:
  push:
    branches: [deploy]

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test all services
        run: mvn clean install

      - name: Run integration tests
        run: mvn verify
