name: Feature branch check

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test all microservices
        run: |
          for d in */; do
            if [ -f "$d/pom.xml" ]; then
              echo "🔨 Buduję $d"
              mvn -f "$d/pom.xml" clean install
            fi
          done
  deploy-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application
        run: |
          ssh user@your.server.com "cd /path/to/app && git pull origin feature/branch && ./restart.sh"