name: Feature branch check

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test all microservices
        run: |
          for d in */; do
            if [ -f "$d/pom.xml" ]; then
              echo "🔨 Buduję $d"
              mvn -f "$d/pom.xml" clean install
            fi
          done
